### ISSUE TITLE
Request new module: ascent

### ISSUE THREAD

**Issue by NoeSamaille** [cloud-native-toolkit/automation-modules#128]
**Related user story**
[#509](https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/509)

**Type of module**
gitops

**What is the purpose of the module?**
Deploy Ascent tool in OpenShift cluster, by provisionning a GitOps repo with the nescessary resources.

**What is the category of the module?**
sre

**Comment by NoeSamaille** [comment]
@seansund can you approve this request for ascent gitops module?

**Comment by seansund** [comment]
The module has been provisioned - https://github.com/cloud-native-toolkit/terraform-gitops-ascent

@NoeSamaille you should have an invitation maintainer as a maintainer
