### ISSUE TITLE
Request new module: {openldap}

### ISSUE THREAD

**Issue by balasgit** [cloud-native-toolkit/automation-modules#129]
**Related user story**
https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/510

**Type of module**
Both Terraform & GitOPs

**If requesting a terraform module, what is the target cloud platform?**
IBM Cloud

**What is the purpose of the module?**
Install LDAP on Openshift

**What is the category of the module?**
LDAP

**Comment by seansund** [comment]
Module created in repo - https://github.com/cloud-native-toolkit/terraform-gitops-openldap
