### ISSUE TITLE
Request new module: storge class gitops

### ISSUE THREAD

**Issue by tcskill** [cloud-native-toolkit/automation-modules#130]
**Related user story**
[490](https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/490)

**Type of module**
gitops

**If requesting a terraform module, what is the target cloud platform?**
all

**What is the purpose of the module?**
create a storage class on ocp

**What is the category of the module?**
cluster

**Comment by seansund** [comment]
Created repostory - https://github.com/cloud-native-toolkit/terraform-gitops-ocp-storageclass
