### ISSUE TITLE
Request new module: cert manager for mas

### ISSUE THREAD

**Issue by tcskill** [cloud-native-toolkit/automation-modules#131]
**Related user story**
493

**Type of module**
gitops

**If requesting a terraform module, what is the target cloud platform?**
all

**What is the purpose of the module?**
deploy cert-mgr as part of a mas / maximo install

**What is the category of the module?**
middleware

**Comment by seansund** [comment]
Provided repo - https://github.com/cloud-native-toolkit/terraform-gitops-cp-cert-manager
