### ISSUE TITLE
Request new module: Module to provision Bastion service on AWS

### ISSUE THREAD

**Issue by Sivasaivm** [cloud-native-toolkit/automation-modules#132]
**Related user story**
Module to provision Bastion service on AWS - #480

**Type of module**
terraform 

**If requesting a terraform module, what is the target cloud platform?**
 aws

**What is the purpose of the module?**
Module to provision Bastion service on AWS

**What is the category of the module?**
infrastructure

**Comment by seansund** [comment]
Provided repo - https://github.com/cloud-native-toolkit/terraform-aws-bastion

@Sivasaivm You have been added to the repo with Maintainer access
