### ISSUE TITLE
Request new module: Provision VPC subnet on AWS

### ISSUE THREAD

**Issue by indirakalagara** [cloud-native-toolkit/automation-modules#134]
**Related user story**
Provision VPC subnet on AWS #522

**Type of module**
terraform 

**If requesting a terraform module, what is the target cloud platform?**
aws

**What is the purpose of the module?**
Provision VPC subnet on AWS 

**What is the category of the module?**
infrastructure

**Comment by seansund** [comment]
Repo created - https://github.com/cloud-native-toolkit/terraform-aws-vpc-subnets

@indirakalagara You have been invited to be an admin of the repo
