### ISSUE TITLE
Request new module: provision DB2 from CP4D via gitops

### ISSUE THREAD

**Issue by RamyaRaghuveera** [cloud-native-toolkit/automation-modules#137]
**Related user story**
https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/491

**Type of module**
   gitops

**If requesting a terraform module, what is the target cloud platform?**
ibm, aws, azure, etc

**What is the purpose of the module?**
Module to deploy DB2 from CP4D via gitops

**What is the category of the module?**
 database

**Comment by seansund** [comment]
Repo created - https://github.com/cloud-native-toolkit/terraform-gitops-cp-db2
