### ISSUE TITLE
Request new module: ODM

### ISSUE THREAD

**Issue by yogendrasri** [cloud-native-toolkit/automation-modules#138]
**Related user story**
https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/506)

**Type of module**
 gitops

**If requesting a terraform module, what is the target cloud platform?**
ibm, aws, azure, etc

**What is the purpose of the module?**
automate ODM

**What is the category of the module?**
software

**Comment by seansund** [comment]
Repo created - https://github.com/cloud-native-toolkit/terraform-gitops-cp-odm
