### ISSUE TITLE
Request new module: db2-schema

### ISSUE THREAD

**Issue by RamyaRaghuveera** [cloud-native-toolkit/automation-modules#139]
**Related user story**
https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/503

**Type of module**
gitops

**If requesting a terraform module, what is the target cloud platform?**
ibm, aws, azure, etc

**What is the purpose of the module?**
Module will deploy DB2 schemas in DB2

**What is the category of the module?**
 database

**Comment by seansund** [comment]
Created repo - https://github.com/cloud-native-toolkit/terraform-gitops-db2-schema
