### ISSUE TITLE
Request new module: gitops module for SLS service for Maximo

### ISSUE THREAD

**Issue by RamyaRaghuveera** [cloud-native-toolkit/automation-modules#140]
**Related user story**
https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/527
**Type of module**
 gitops

**If requesting a terraform module, what is the target cloud platform?**
ibm, aws, azure, etc

**What is the purpose of the module?**
To create an IBM SLS service for Maximo

**What is the category of the module?**
Operator, Cluster

**Comment by seansund** [comment]
Repo created - https://github.com/cloud-native-toolkit/terraform-gitops-cp-sls
