### ISSUE TITLE
Request new module: DB2 instance

### ISSUE THREAD

**Issue by yogendrasri** [cloud-native-toolkit/automation-modules#168]
**Related user story**
https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/552

Type of module
gitops

If requesting a terraform module, what is the target cloud platform?
ibm, aws, azure, etc

What is the purpose of the module?
deploy DB2 instance on openShift

What is the category of the module?
database

**Comment by triceam** [comment]
done: https://github.com/cloud-native-toolkit/terraform-gitops-db2-instance
