### ISSUE TITLE
Request new module: cp-data-fabric

### ISSUE THREAD

**Issue by sgumpana** [cloud-native-toolkit/automation-modules#192]
**Related user story**
[Issue 566](https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/566)

**Type of module**
gitops

**If requesting a terraform module, what is the target cloud platform?**
ibm

**What is the purpose of the module?**
Data Fabric Solution Automation. This module performs the following steps to configure and setup Data Fabric Solution on Cloud pak for Data.
- Login to Cloud pak for Data and get the token
- Create Users in Cloud pak for Data
- Create Amazon S3 Platform connection in Cloud pak for Data
- Create Analytics Project in Cloud pak for Data
- Virtualize files from DV
- Create Join
- Create Category,  Classification,  Business Term,  Reference Data,  Data Class,  Data Protection Rule
- Add Connection to Catalog, Add Connected asset to Catalog, Add users to Catalog
- Create Auto AI Experiment (Create Space, Create Pipeline, Create Data Asset, Create & Upload Attachment, Create Training and Deploy Model)

**What is the category of the module?**
application

**Comment by triceam** [comment]
Copying in content from the email here:

> As discussed, sharing the dependent modules and Execution Flow for Data Fabric Solution Automation.
> Please approve (terraform-gitops-data-fabric-https://github.com/cloud-native-toolkit/automation-modules/issues/192)
>  
> Dependent Modules:
> 
> 1. GitOps modules
> 2. OCP Cluster
> 3. Create AWS Bucket
> 4. Create Azure DB
> 5. Configure Cluster to Pull images 
> 6. Cloud Pak Foundational Services
> 7. CP4D Operator Subscriptions
> 8. Cloud Pak for Data
> 9. Install Data Virtualization
> 10. Install WKC
> 11. Install WS
> 12. Install WML
> 13. Provision Data Virtualization Instance in CPD
> 14. Configure Data Fabric Solution (terraform-gitops-data-fabric-https://github.com/cloud-native-toolkit/automation-modules/issues/192)
> 15. Bill of Materials for Data Fabric Solution
> 
>  
> Execution Flow:
>  
> ![image](https://user-images.githubusercontent.com/974294/151568971-5951223f-5d57-49d3-ad2f-3eafc5e074aa.png)
>

**Comment by sgumpana** [comment]
Sean can you approve this ? this is pending from last 10 days. We are blocked on this.
