### ISSUE TITLE
Request new module: terraform-gitops-data-virtualization

### ISSUE THREAD

**Issue by spansare** [cloud-native-toolkit/automation-modules#202]
**Related user story**
https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/586

**Type of module**
gitops

**If requesting a terraform module, what is the target cloud platform?**
cloudpak

**What is the purpose of the module?**
Purpose of this module is to provision a Data Virtualization instance on Cloud Pak for Data.

**What is the category of the module?**
service

**Comment by triceam** [comment]
Repo renamed to https://github.com/cloud-native-toolkit/terraform-gitops-data-virtualization

**Comment by seansund** [comment]
@spansare invited to repo with write access
