### ISSUE TITLE
Request new module: cp-data-virtualization

### ISSUE THREAD

**Issue by sgumpana** [cloud-native-toolkit/automation-modules#211]
**Related user story**
[Issue 543](https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/543)

**Type of module**
 gitops

**If requesting a terraform module, what is the target cloud platform?**
ibm

**What is the purpose of the module?**
Terraform module to install DV in CP4D. (https://www.ibm.com/docs/en/cloud-paks/cp-data/4.0?topic=services-data-virtualization)

**What is the category of the module?**
service

**Comment by sgumpana** [comment]
Note: this is to install Data Virtualization on CP4D. (https://www.ibm.com/docs/en/cloud-paks/cp-data/4.0?topic=services-data-virtualization)
This is different from https://github.com/cloud-native-toolkit/terraform-gitops-data-virtualization (Provision DV instance inside CP4D. (https://www.ibm.com/docs/en/cloud-paks/cp-data/4.0?topic=virtualization-provisioning-service))

**Comment by seansund** [comment]
@sgumpana invited to repo with write access
