### ISSUE TITLE
Request new module: cp-watson-studio

### ISSUE THREAD

**Issue by sgumpana** [cloud-native-toolkit/automation-modules#212]
**Related user story**
[Issue 533](https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/533)

**Type of module**
 gitops

**If requesting a terraform module, what is the target cloud platform?**
ibm

**What is the purpose of the module?**
GitOps module to install Watson Studio on CP4D (https://www.ibm.com/docs/en/cloud-paks/cp-data/4.0?topic=studio-installing-watson)

**What is the category of the module?**
service

**Comment by seansund** [comment]
@sgumpana invited to repo with write access
