### ISSUE TITLE
Request new module: cp-watson-machine-learning

### ISSUE THREAD

**Issue by spansare** [cloud-native-toolkit/automation-modules#215]
**Related user story**
https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/588

**Type of module**
gitops

**If requesting a terraform module, what is the target cloud platform?**
ibm

**What is the purpose of the module?**
Gitops module to install Watson Machine Learning on Cloud Pak for Data

**What is the category of the module?**
service

**Comment by seansund** [comment]
@spansare has been invited to the repo
