### ISSUE TITLE
Request new module: aws-s3-bucket

### ISSUE THREAD

**Issue by sgumpana** [cloud-native-toolkit/automation-modules#221]
**Related user story**
[Issue 554 - Module to provision AWS S3 bucket](https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/554)

**Type of module**
terraform

**If requesting a terraform module, what is the target cloud platform?**
aws

**What is the purpose of the module?**
Module to provision AWS S3 bucket

**What is the category of the module?**
database

**Comment by seansund** [comment]
@sgumpana added to repo with write permissions
