### ISSUE TITLE
Request new module: gitops module for Event stream instance in cp4i

### ISSUE THREAD

**Issue by JyotiRani** [cloud-native-toolkit/automation-modules#222]
**Related user story**
New issue

**Type of module**
gitops

**If requesting a terraform module, what is the target cloud platform?**
ibm, aws, azure, etc

**What is the purpose of the module?**
Create Event Streams instance as part of cloud pak for integration

**What is the category of the module?**
integration

**Comment by seansund** [comment]
This is a duplicate of https://github.com/cloud-native-toolkit/automation-modules/issues/189 which has already been created and to which @JyotiRani you have already been added as a collaborator

**Comment by JyotiRani** [comment]
@seansund #189 is to create the Event Stream operator (CRD), while this module is to create an instance (CR) of the Event Streams hence i created a separate module for it. Plz verify and confirm.

**Comment by JyotiRani** [comment]
@seansund can you please approve this module?
