### ISSUE TITLE
Request new module: CP4BA - IBM Automation Foundation Operator

### ISSUE THREAD

**Issue by dineshchandrapandey** [cloud-native-toolkit/automation-modules#232]
**Related user story**
Provide the issue number for the user story related to this request #603

**Type of module**
gitops

**If requesting a terraform module, what is the target cloud platform?**
ibm

**What is the purpose of the module?**
Gitops Module to provision CP4BA - IBM Automation Foundation Operator

**What is the category of the module?**
middleware

**Comment by indirakalagara** [comment]
Please add below collaborators 
 @indirakalagara @dineshchandrapandey @saratrip  @DileepPaul

**Comment by seansund** [comment]
/displayName Cloud Pak for Business Automation operator

**Comment by indirakalagara** [comment]
@seansund  Can you please rename the repo to terraform-gitops-cp-iaf-operator
