### ISSUE TITLE
Gitops Module to provision CP4BA - IBM Business Automation Navigator and UMS Operator

### ISSUE THREAD

**Issue by saratrip** [cloud-native-toolkit/automation-modules#234]
**Related user story**
Gitops Module to create Instance of IBM Business Automation Operator #604

**Type of module**
terraform or gitops

**If requesting a terraform module, what is the target cloud platform?**
ibm, aws, azure, etc

**What is the purpose of the module?**
Please describe what this automation module will do

**What is the category of the module?**
cluster, iam, network, database, integration, dev-tool, sre, infrastructure, util

**Comment by indirakalagara** [comment]
Please add below collaborators 
 @indirakalagara @dineshchandrapandey @saratrip  @DileepPaul

**Comment by seansund** [comment]
/displayName IBM Business Automation Navigator and UMS operator
