### ISSUE TITLE
New new module: cp-apic

### ISSUE THREAD

**Issue by vksuktha** [cloud-native-toolkit/automation-modules#241]
**Related User Story**
https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/634

**Type of module**
 gitops

**If requesting a terraform module, what is the target cloud platform?**
ibm, aws, azure, etc

**What is the purpose of the module?**
Create IBM Cloud Pak for APIC instance

**What is the category of the module?**
Middleware

**Comment by seansund** [comment]
Renaming the existing `gitops-cp-apic` to `gitops-cp-apic-operator` module before creating this one as `gitops-cp-apic`
