### ISSUE TITLE
Request new module: db2-schema

### ISSUE THREAD

**Issue by RamyaRaghuveera** [cloud-native-toolkit/automation-modules#246]
**Related user story**
https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/503
**Type of module**
gitops

**If requesting a terraform module, what is the target cloud platform?**
ibm

**What is the purpose of the module?**
Create DB2 schema for DB2 database

**What is the category of the module?**
database

Please delete the existing repo https://github.com/cloud-native-toolkit/terraform-gitops-db2-schema and create a new one with the latest version of the template.

**Comment by seansund** [comment]
Repo created - https://github.com/cloud-native-toolkit/terraform-gitops-db2-schema
