### ISSUE TITLE
Request new module: cp-ace-dashboard

### ISSUE THREAD

**Issue by gowdhaman-j** [cloud-native-toolkit/automation-modules#247]
**Related user story**
Issue #: 635 & Issue Name: https://github.ibm.com/gsi-labs/industry-cloud-planning/issues/635

**Type of module**
gitops

**If requesting a terraform module, what is the target cloud platform?**
ibm, aws, azure, etc

**What is the purpose of the module?**
This module provides an Integration administrator to manage and monitor the AppConnect Enterprise instances ( Toolkit Flow based implementation)

**What is the category of the module?**
integration

**Comment by seansund** [comment]
Repo created - https://github.com/cloud-native-toolkit/terraform-gitops-cp-ace-dashboard
