### ISSUE TITLE
Request new module: AWS VPC to VPC Peering

### ISSUE THREAD

**Issue by Sivasaivm** [cloud-native-toolkit/automation-modules#272]
**Related user story**
 
Issue number - 704

**Type of module**
terraform 

**If requesting a terraform module, what is the target cloud platform?**
aws

**What is the purpose of the module?**
Create a terraform automation module for AWS VPC to VPC Peering.

**What is the category of the module?**
cluster, network & infrastructure

**Comment by seansund** [comment]
duplicate
